src/AppBundle/Twig/AppExtension.php, src/AppBundle/Twig/Extension.php
@MusikAnimal requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/wikimedia/grantmetrics/
=> Scrutinizer Auto-Fixes

README.md, src/AppBundle/Model/Event.php, src/AppBundle/Model/EventStat.php, src/AppBundle/Model/EventWiki.php, src/AppBundle/Model/Organizer.php, src/AppBundle/Model/Participant.php, src/AppBundle/Model/Program.php, tests/AppBundle/Model/EventStatTest.php, tests/AppBundle/Model/EventTest.php, tests/AppBundle/Model/EventWikiTest.php, tests/AppBundle/Model/OrganizerTest.php, tests/AppBundle/Model/ParticipantTest.php, tests/AppBundle/Model/ProgramTest.php
Basic README for setting up the app, hopefully is accurate
=> Add add/remove methods to models with associations

app/config/config.yml, build/ci/install-mediawiki.sh, i18n/en.json, i18n/qqq.json, src/AppBundle/Controller/EventController.php, src/AppBundle/Model/EventWiki.php, src/AppBundle/Repository/EventWikiRepository.php, src/AppBundle/Repository/Repository.php, src/AppBundle/Twig/AppExtension.php, tests/AppBundle/Controller/EventControllerTest.php
Fix bug with msgIfExists Intuition helper.
=> Events: validate the associated event wikis

README.md, app/DoctrineMigrations/Version20171213234700.php, app/Resources/assets/css/events.scss, app/Resources/assets/js/events.js, app/Resources/views/blocks/forms.html.twig, app/Resources/views/events/_form.html.twig, app/Resources/views/events/show.html.twig, i18n/en.json, i18n/qqq.json, src/AppBundle/Controller/EventController.php, src/AppBundle/Model/Event.php, tests/AppBundle/Controller/EventControllerTest.php
Some hackery to make i18n from constraint annotation work
=> Events: require a start/end time, add validations with i18n

app/Resources/assets/css/application.scss, app/Resources/views/programs/index.html.twig, app/Resources/views/programs/show.html.twig, i18n/en.json, i18n/qqq.json
Tweak text-wrap; Don't show empty table for no events in program
Fix alignment issues and column overflow
=> Fix alignment issues and column overflow

app/Resources/views/programs/index.html.twig, i18n/en.json, i18n/qqq.json, src/AppBundle/Controller/DefaultController.php, src/AppBundle/Controller/EntityController.php, src/AppBundle/Controller/EventController.php, src/AppBundle/Controller/EventDataController.php, src/AppBundle/Controller/ProgramController.php, src/AppBundle/EventSubscriber/AuthenticationSubscriber.php, tests/AppBundle/Controller/DatabaseAwareWebTestCase.php, tests/AppBundle/Controller/EventControllerTest.php, tests/AppBundle/Controller/EventDataControllerTest.php, tests/AppBundle/Controller/ProgramControllerTest.php
New abstract EntityController for refactoring Event, EventData and
Program controllers.
Show message instead of empty table on Programs index page.
Bug: https://phabricator.wikimedia.org/T182888
=> Require login on all pages but the homepage

src/AppBundle/Controller/EventDataController.php, src/AppBundle/DataFixtures/MediaWiki/post-install.sql, src/AppBundle/Model/EventWiki.php, src/AppBundle/Service/EventProcessor.php, tests/AppBundle/Controller/EventControllerTest.php, tests/AppBundle/Model/EventWikiTest.php
Bug: https://phabricator.wikimedia.org/T199289
=> Don't remove orphan wikis when generating stats

src/AppBundle/Repository/ProgramRepository.php
Doctrine was unnecessarily scanning other tables. Raw SQL is
much faster in this case.
Bug: https://phabricator.wikimedia.org/T200478
=> Don't use Doctrine query builder when fetching unique event wiki stats

phpcs.xml, src/AppBundle/Repository/EventWikiRepository.php, tests/AppBundle/Twig/FormatExtensionTest.php
Are sniff transgressions called sniffles?
=> Add new sniff for concatenation spacing, and fix errors

README.md
An attempt to document the developer's installation process from
the beginning, assuming as little as possible.
=> More detailed installation notes

src/AppBundle/Model/EventWiki.php, src/AppBundle/Repository/EventCategoryRepository.php, src/AppBundle/Repository/EventRepository.php, src/AppBundle/Service/EventProcessor.php, tests/AppBundle/Command/ProcessEventCommandTest.php
Bug: https://phabricator.wikimedia.org/T194707
=> Add category support to queries for pages created/improved

app/Resources/assets/css/events.scss, app/Resources/views/events/show.html.twig, i18n/en.json, i18n/qqq.json
Bug: https://phabricator.wikimedia.org/T200477
=> Add 'Statistics' header to stats part of the event page

.scrutinizer.yml, .travis.yml, composer.json, composer.lock, phpunit.xml.dist, tests/AppBundle/Command/ProcessEventCommandTest.php, tests/AppBundle/Model/EventTest.php
Doctrine\ORM\EntityRepository::findOneBy() returns NULL if nothing
is found, and as of PHP 7.2 this isn't countable.
Also add PHP 7.2 to CI, for future bug-catching.
I'm not sure if we want to bother about 7.2... but i'm using it locally, so this was bugging me.
=> Fix countable error for PHP 7.2

composer.lock, src/AppBundle/Controller/EntityController.php
This will be used when manually doing validations, instead of using
Symfony forms.
Update composer.lock
=> Add ValidatorInterface as an EntityController class property

app/Resources/views/events/show.html.twig, src/AppBundle/Model/Event.php
Bug: https://phabricator.wikimedia.org/T201739
=> Use timezone-adjusted start date when checking if stats can be generated

.travis.yml, composer.json, composer.lock
Update doctrine/coding-standard and phpunit
=> Require ext-redis in composer.json

app/Resources/views/events/revisions.wikitext.twig, src/AppBundle/Controller/EventDataController.php, tests/AppBundle/Controller/EventDataControllerTest.php
Bug: https://phabricator.wikimedia.org/T202707
=> Fix variable naming in revision wikitext export

composer.json, composer.lock, src/AppBundle/DataFixtures/ORM/LoadFixtures.php, src/AppBundle/DataFixtures/ORM/extended.yml
I'm not quite sure this is the fully best way, but it works and doesn't resort to the extra dependency that I think is the proper way. :)
Bug: https://phabricator.wikimedia.org/T203139
=> Update Alice to most recent version

.codeclimate.yml, app/Resources/views/base.html.twig, app/Resources/views/default/index.html.twig, app/config/services.yml, src/AppBundle/Controller/Controller.php, src/AppBundle/Controller/DefaultController.php, src/AppBundle/Controller/EntityController.php, src/AppBundle/Controller/EventController.php, src/AppBundle/Controller/ProgramController.php, src/AppBundle/Service/Intuition.php, src/AppBundle/Twig/Extension.php, tests/AppBundle/Twig/AppExtensionTest.php, tests/AppBundle/Twig/FormatExtensionTest.php
Bug: https://phabricator.wikimedia.org/T203421
=> Move Intuition to be a service, and inject it where required

app/config/config.yml, app/config/parameters-travis.yml.dist, app/config/parameters.yml.dist
This is just an idea I've got about making it email us critical errors.
=> Add config for custom sendmail config (for Toolforge)

.minus-x.json, README.md, composer.json, composer.lock
Add 'composer fix' task to automatically fix some linting/MinusX errors.
Update README, fix typos.
=> Add MinusX test to check for files that shouldn't be executable

composer.json, composer.lock
Hardcode Symfony version to avoid an upgrade to 4.2.
=> Bump Composer packages

src/AppBundle/Controller/EventDataController.php
This is a follow-up to #146. We don't need to use the
KernelEvents::TERMINATE event to start the job spawning process. This
endpoint is called only by AJAX, so we can simply end the user session
which effectively backgrounds that process (the web request) which
spawns the job.
Bug: https://phabricator.wikimedia.org/T192954
=> End user session to background job spawn process

.codeclimate.yml, app/DoctrineMigrations/Version20181213234624.php, src/AppBundle/Model/EventWiki.php, src/AppBundle/Repository/EventWikiRepository.php, src/AppBundle/Service/EventProcessor.php, tests/AppBundle/Model/EventWikiTest.php, tests/AppBundle/Repository/EventWikiRepositoryTest.php
Bug: https://phabricator.wikimedia.org/T206817
=> Split page IDs into 'created' and 'improved'

app/Resources/views/base.html.twig
Bug: https://phabricator.wikimedia.org/T213735
=> Add code to track usage to piwik.wikimedia.org

i18n/en.json, i18n/qqq.json, src/AppBundle/Model/Event.php, src/AppBundle/Model/EventStat.php, src/AppBundle/Model/EventWikiStat.php, src/AppBundle/Repository/EventRepository.php, src/AppBundle/Repository/EventWikiRepository.php, src/AppBundle/Repository/Repository.php, src/AppBundle/Service/EventProcessor.php, tests/AppBundle/Command/ProcessEventCommandTest.php, tests/AppBundle/Controller/EventDataControllerTest.php, tests/AppBundle/Model/EventTest.php
Bug: https://phabricator.wikimedia.org/T206820
=> Byte difference stat

src/AppBundle/Service/JobHandler.php
Apparently simply rethrowing the exception doesn't work. This is better
anyway because we have an easy-to-read subject line for job failures.
=> Fix email notifications of job failures

app/config/services.yml, src/AppBundle/Model/Event.php, src/AppBundle/Model/EventStat.php, src/AppBundle/Model/EventWikiStat.php, src/AppBundle/Repository/EventWikiRepository.php, src/AppBundle/Repository/PageviewsRepository.php, src/AppBundle/Service/EventProcessor.php, tests/AppBundle/Command/ProcessEventCommandTest.php, tests/AppBundle/Controller/EventDataControllerTest.php, tests/AppBundle/Model/EventTest.php, tests/AppBundle/Repository/PageviewsRepositoryTest.php
Bug: https://phabricator.wikimedia.org/T206817
=> Add pageviews stats

app/Resources/views/base.html.twig
=> Don't send usage stats to piwik for admins

.codeclimate.yml, app/Resources/views/events/_stats_summary.html.twig, app/Resources/views/events/event_summary.wikitext.twig, app/Resources/views/events/show.html.twig, app/Resources/views/programs/index.html.twig, app/Resources/views/programs/show.html.twig, src/AppBundle/DataFixtures/ORM/extended.yml, src/AppBundle/Model/Event.php, src/AppBundle/Model/EventStat.php, src/AppBundle/Repository/EventRepository.php, src/AppBundle/Repository/EventWikiRepository.php, src/AppBundle/Repository/ProgramRepository.php, src/AppBundle/Service/EventProcessor.php, tests/AppBundle/Command/ProcessEventCommandTest.php, tests/AppBundle/Controller/EventDataControllerTest.php, tests/AppBundle/Model/EventTest.php
Bug: https://phabricator.wikimedia.org/T208546
=> Participant counts from page IDs

app/Resources/views/base.html.twig
=> Only send usage stats to piwik for logged in users

app/Resources/views/events/revisions.csv.twig, app/Resources/views/events/revisions.wikitext.twig
=> Fix timezone of revision timestamps in revisions wikitext/CSV export

src/AppBundle/Model/Event.php, src/AppBundle/Model/EventStat.php, src/AppBundle/Model/EventWikiStat.php, src/AppBundle/Repository/EventRepository.php, src/AppBundle/Service/EventProcessor.php, tests/AppBundle/Command/ProcessEventCommandTest.php, tests/AppBundle/Model/EventTest.php, tests/AppBundle/Repository/EventRepositoryTest.php
Bug: https://phabricator.wikimedia.org/T215356
=> Count pages with uploaded files

src/AppBundle/Repository/EventRepository.php, src/AppBundle/Service/EventProcessor.php, tests/AppBundle/Command/ProcessEventCommandTest.php
=> Change the pages-improved stat to not count pages created

src/AppBundle/DataFixtures/ORM/extended.yml, src/AppBundle/Repository/EventCategoryRepository.php, src/AppBundle/Repository/EventRepository.php, src/AppBundle/Repository/EventWikiRepository.php, tests/AppBundle/Command/ProcessEventCommandTest.php, tests/AppBundle/Controller/EventDataControllerTest.php, tests/AppBundle/Repository/EventWikiRepositoryTest.php
=> Don't include redirects in all queries

app/Resources/views/base.html.twig, app/config/config.yml, src/AppBundle/Twig/AppExtension.php
This makes it more clear whose work you're testing.
=> Show current branch and link to tree on local/staging within site notice

.scrutinizer.yml, app/Resources/views/events/event_summary.wikitext.twig, app/Resources/views/events/pages_created.wikitext.twig, app/Resources/views/events/revisions.wikitext.twig, app/Resources/views/macros/wiki.html.twig
Wrap <nowiki/> around edit summary in revisions wikitext export
=> Use wiki macros where possible, rm import when not used

app/Resources/views/events/event_summary.csv.twig, i18n/en.json, i18n/qqq.json, src/AppBundle/Controller/EventDataController.php
Bug: https://phabricator.wikimedia.org/T205561
=> Add event summary CSV

app/Resources/views/events/pages_created.csv.twig, i18n/en.json, i18n/qqq.json, src/AppBundle/Controller/EventDataController.php
Minor refactoring in EventDataController
Bug: T206058
=> Pages Created CSV export

src/AppBundle/Controller/EventDataController.php
See https://github.com/wikimedia/eventmetrics/pull/204#discussion_r261463312
=> Remove double quotes from title in CSV file name

src/AppBundle/Repository/EventWikiRepository.php, tests/AppBundle/Controller/EventDataControllerTest.php
Should be in UTC.
Bug: T205502
=> Fix timestamps in Pages Created report query

src/AppBundle/Repository/EventRepository.php, tests/AppBundle/Repository/EventRepositoryTest.php
=> Ensure we only fetch unique pages for 'pages using files' metric

app/Resources/views/events/pages_created.csv.twig
=> Include page creator in Pages Created report

app/Resources/views/events/_header.html.twig
=> Open Wikitext reports in new tab

src/AppBundle/Service/EventProcessor.php
Show counts while iterating through each wiki
=> Better output for EventProcessor

app/Resources/views/events/event_summary.csv.twig, app/Resources/views/events/pages_created.csv.twig, app/Resources/views/events/revisions.csv.twig, src/AppBundle/Twig/AppExtension.php, src/AppBundle/Twig/FormatExtension.php, tests/AppBundle/Twig/FormatExtensionTest.php
Remove extraneous spacing in some CSV reports
Remove unused Twig function
Bug: T215923
=> Add csv() Twig function to properly format CSV cells

src/AppBundle/Controller/EventController.php, tests/AppBundle/Controller/EventControllerTest.php
=> Redirect to Event Summary page after creating/updating event

src/AppBundle/Repository/EventWikiRepository.php, tests/AppBundle/Controller/EventDataControllerTest.php
=> Go by usernames when getting bytes added, if present

src/AppBundle/Controller/ProgramController.php
=> Redirect to Program page after saving

src/AppBundle/Model/EventCategory.php, src/AppBundle/Model/EventWiki.php, src/AppBundle/Repository/EventWikiRepository.php
Some metrics like 'pages-using-files-pageviews-avg' need to look at
all wikis, and not just ones that are configured for the Event.
Bug: T218916
=> Remove wiki validation when fetching domain from input

.codeclimate.yml, app/Resources/views/events/_header.html.twig, app/Resources/views/events/pages_improved.csv.twig, i18n/en.json, i18n/qqq.json, package-lock.json, src/AppBundle/Controller/EventDataController.php, src/AppBundle/Repository/EventRepository.php, src/AppBundle/Repository/EventWikiRepository.php, tests/AppBundle/Controller/EventDataControllerTest.php
Bug: https://phabricator.wikimedia.org/T210775
=> Add pages improved CSV report

app/Resources/views/events/_categories.html.twig, app/Resources/views/events/_participants.html.twig
Bug: https://phabricator.wikimedia.org/T219464
=> Don't collapse categories/participants on error

app/Resources/views/events/pages_created.wikitext.twig, app/Resources/views/events/pages_improved.wikitext.twig
Also fix an always plus issue in pages created.
Bug: https://phabricator.wikimedia.org/T210898
=> Add pages improved wikitext report

app/Resources/views/events/_wiki_table.html.twig
=> Include Wikidata in per-wiki metrics table

app/Resources/views/events/_metadata.html.twig
=> Nowrap labels in Event Summary page metadata

app/Resources/views/events/show.html.twig
=> Don't display "Event settings saved successfully" on errors

src/AppBundle/Repository/EventWikiRepository.php
Avg pageviews are always a 31-day window, and not since the start
of the event.
Bug: T219650
=> Fix fetching of average pageviews for Pages Improved report

src/AppBundle/Repository/EventRepository.php
=> Use blank string for summary when NULL

app/Resources/views/events/pages_created.csv.twig, app/Resources/views/events/pages_created.wikitext.twig, app/Resources/views/events/pages_improved.csv.twig, app/Resources/views/events/pages_improved.wikitext.twig, app/Resources/views/macros/wiki.html.twig, src/AppBundle/Twig/FormatExtension.php, tests/AppBundle/Controller/EventDataControllerTest.php, tests/AppBundle/Twig/FormatExtensionTest.php
=> Fix page encoding

src/AppBundle/Twig/FormatExtension.php, tests/AppBundle/Twig/FormatExtensionTest.php
=> Support negative abbreviate numbers

i18n/en.json
=> Update pages-using-files-desc message

src/AppBundle/Service/EventProcessor.php
Tested by inserting a 15 minutes sleep.
Bug: T219897
=> Reconnect timed out database connections

src/AppBundle/Controller/EventDataController.php, src/AppBundle/Model/Job.php
=> Bump time limit for jobs to 30 minutes

i18n/en.json
=> Fix incorrect message about files uploaded

src/AppBundle/Controller/EventDataController.php
It just seems way more stable for slow jobs.
The numbers for cutoff are chosen based on statistics:
* Most events don't have a single category, so 1 category is already a lot
* There are ~30 participants per event on average
* Average event lasts for less than an hour (eh?)
Bug: T220463
=> Always process some events via cronjob

src/AppBundle/Repository/EventRepository.php, src/AppBundle/Service/EventProcessor.php
=> More actor migration

src/AppBundle/Repository/EventRepository.php
=> Finish actorifyting EventRepository

composer.lock
=> Bump Symfony core
