src/AppBundle/Model/Event.php, src/AppBundle/Model/EventCategory.php, src/AppBundle/Model/EventWiki.php, tests/AppBundle/Command/ProcessEventCommandTest.php, tests/AppBundle/Command/SpawnJobsCommandTest.php, tests/AppBundle/Controller/DatabaseAwareWebTestCase.php, tests/AppBundle/GrantMetricsTestCase.php, tests/AppBundle/Model/EventCategoryTest.php, tests/AppBundle/Model/EventStatTest.php, tests/AppBundle/Model/EventTest.php, tests/AppBundle/Model/EventWikiStatTest.php, tests/AppBundle/Model/EventWikiTest.php, tests/AppBundle/Model/JobTest.php, tests/AppBundle/Model/OrganizerTest.php, tests/AppBundle/Model/ParticipantTest.php, tests/AppBundle/Model/ProgramTest.php, tests/AppBundle/Twig/AppExtensionTest.php, tests/AppBundle/Twig/FormatExtensionTest.php
Make all tests extend GrantMetricsTestCase, which sets the default timezone.
=> Add missing methods for EventCategory and EventWiki relationship

app/Resources/assets/css/events.scss, app/Resources/views/events/_participants.html.twig
But still list the invalid participants above the textarea. This
change also changes the participants form from being a horizontal
form (in Bootstrap parlance) and so adds .row divs where required;
this means some styling can be removed.
Bug: https://phabricator.wikimedia.org/T200544
=> Move new-participants textarea above list of existing participants

src/AppBundle/Controller/EventController.php, tests/AppBundle/Controller/EventControllerTest.php
Re-order the validation process of participant usernames.
Bug: https://phabricator.wikimedia.org/T201577
=> Remove duplicate usernames after normalizing

.travis.yml, README.md, composer.json
Just investigating this:
> $ ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
> Error: could not find any viable formatter. available formatters: clover, cobertura, coverage.py, excoveralls, gcov, gocov, jacoco, lcov, simplecov
And also the badge URLs.
=> [WiP] Fix Code Climate integration

composer.json, src/AppBundle/Controller/DefaultController.php, src/AppBundle/Repository/EventWikiRepository.php, tests/AppBundle/Controller/DefaultControllerTest.php
This will be used in clientside JavaScript for autocompletion on wiki
inputs. We can't go by the Sitematrix API because newly introduced wikis
may be production but not yet on the replicas, causing Grant Metrics to
error out.
This commit also adds ext-json as a dependency in composer.json, along
with some unrelated minor code aesthetics.
=> API endpoint to get all wikis adhering to EventWiki::VALID_WIKI_PATTERN

app/Resources/assets/js/application.js, app/config/config.yml, src/AppBundle/Model/Traits/TitleUserTrait.php, tests/AppBundle/Model/ProgramTest.php
This replaces 4-byte utf8 characters (i.e. emojis, basically) in
model titles with the unicode replacement character.
Bug: https://phabricator.wikimedia.org/T201388
=> Remove high unicode characters from model titles

.gitignore, .travis.yml, README.md, app/AppKernel.php, app/Resources/assets/js/application.js, app/Resources/assets/js/dateLocales.js, app/Resources/assets/js/events.js, app/Resources/assets/js/programs.js, app/Resources/views/base.html.twig, app/config/config.yml, composer.json, composer.lock, deploy.sh, package-lock.json, package.json, webpack.config.js
In preparation for upgrading to Symfony 4, remove Assetic and
install Webpack Encore. This entails a few changes:
* give global functions an application scope;
* introduce npm
* deployment process changes
Bug: https://phabricator.wikimedia.org/T202471
=> Switch from Assetic to Webpack Encore

.gitignore, .phpcs.xml, .travis.yml, build/phpdoc-install.php, composer.json, phpdoc.dist.xml
Temporarily removing phpdoc checkstyle from Travis CI because it
wasn't checking correctly anyway (was always successful).
Moved other phpdoc config into phpdoc.dist.xml
=> Improve phpdoc installation and configuration

app/DoctrineMigrations/Version20180921215535.php, app/config/services.yml, src/AppBundle/EventSubscriber/CategorySubscriber.php, src/AppBundle/Model/Event.php, src/AppBundle/Model/EventCategory.php, src/AppBundle/Repository/EventCategoryRepository.php, src/AppBundle/Repository/EventRepository.php, src/AppBundle/Service/EventProcessor.php, tests/AppBundle/Controller/EventControllerTest.php, tests/AppBundle/Model/EventCategoryTest.php
Remove invalid categories upon saving Event
Rework EventWikiRepository::getDbName to go off of a domain and not an EventWiki object, since
EventCategory is not tied to an EventWiki.
Bug: https://phabricator.wikimedia.org/T194707
=> Store category IDs as well as titles, add subscriber to set the ID

src/AppBundle/Controller/EventController.php, src/AppBundle/Controller/EventDataController.php, src/AppBundle/Model/Event.php, src/AppBundle/Service/EventProcessor.php, src/AppBundle/Service/JobHandler.php, tests/AppBundle/Model/EventTest.php
This is a cheap way around our inability to have cronjobs within the
php7.2 container on Toolforge. Ideally we'd *start* old unstarted jobs
by calling JobHandler::spawnAll(), but we can't do this from a web
request without generating all the stats, meaning the user will have
to wait before the page even loads.
Bug: https://phabricator.wikimedia.org/T192954
=> Kill stale jobs when viewing event page / revision browser

app/Resources/views/events/edit.html.twig, app/Resources/views/events/new.html.twig, app/Resources/views/events/revisions.html.twig, app/Resources/views/events/show.html.twig, app/Resources/views/programs/edit.html.twig, app/Resources/views/programs/index.html.twig, app/Resources/views/programs/show.html.twig, composer.json, composer.lock
Wrap all user-generated content in bdi tags, so that directionality
is preserved even when read through other interface languages.
More specifically, event and program names in Farsi, Arabic or
Hebrew (RTL) will be desplayed correctly even if the user
viewing them in English (LTR)
**
Depends on merging the pull request on ToolforgeBundle first. 
https://github.com/wikimedia/ToolforgeBundle/pull/6
**
See Phabricator task: https://phabricator.wikimedia.org/T205172
=> Add 'bdi' Twig function, and use it for user-generated text

src/AppBundle/Model/Event.php, src/AppBundle/Model/Program.php, src/AppBundle/Repository/EventRepository.php, src/AppBundle/Repository/Repository.php
Remove unused 'use' statements
Bug: https://phabricator.wikimedia.org/T208998
=> Fix accepted types for query timeout, with -1 as no timeout

app/Resources/views/events/_stats_summary.html.twig, app/Resources/views/events/_wiki_table.html.twig, app/Resources/views/events/show.html.twig, app/Resources/views/programs/index.html.twig, app/Resources/views/programs/show.html.twig, src/AppBundle/Controller/ProgramController.php, src/AppBundle/Model/Event.php, src/AppBundle/Model/Traits/EventStatTrait.php
This hides the "Edits" metric that was added with #140, bringing the
interface to what it is currently in production.
This commit does not use the VISIBLE_METRICS constant in the
downloadable reports and wikitext export.
Bug: https://phabricator.wikimedia.org/T207909
=> Use constant to define what metrics should be shown in the interface

app/DoctrineMigrations/Version20181121161847.php, composer.json, composer.lock, src/AppBundle/Model/Event.php, src/AppBundle/Model/EventWiki.php, src/AppBundle/Repository/EventCategoryRepository.php, src/AppBundle/Repository/EventRepository.php, src/AppBundle/Repository/EventWikiRepository.php, src/AppBundle/Repository/Repository.php, src/AppBundle/Service/EventProcessor.php, src/AppBundle/Twig/FormatExtension.php, tests/AppBundle/Controller/DatabaseAwareWebTestCase.php, tests/AppBundle/Controller/EventDataControllerTest.php, tests/AppBundle/Model/EventWikiTest.php
This does not include logic to determine when the stored page IDs
should be used, or when they should be refreshed. Instead it regenerates
them every time stats are regenerated.
Other various code cleanup and minor bug fixes.
Bug: https://phabricator.wikimedia.org/T207989
=> Store/cache page IDs to speed up queries

app/config/parameters-travis.yml.dist, app/config/parameters.yml.dist, src/AppBundle/Controller/DefaultController.php, src/AppBundle/Controller/EntityController.php, src/AppBundle/Controller/EventController.php, src/AppBundle/Controller/EventDataController.php, src/AppBundle/Controller/ProgramController.php, tests/AppBundle/Controller/EventControllerTest.php, tests/AppBundle/Controller/EventDataControllerTest.php
In Symfony 4 trailing slashes automatically redirect to the same route
without the slash. In Symfony 4.1.9 something else changed that caused
our manually added trailing slash routes to fail.
This commit removes all trailing slash routes and fixes the integration
tests accordingly.
=> Remove trailing slash routes and fix tests

app/config/services.yml, src/AppBundle/Logger/WebRequestProcessor.php
By defualt the error reports only include the exception info, time,
among other basic things. We want the URI especially so we can more
easily diagnose what went wrong.
This host is included to distinguish production errors from staging.
=> Include the host and URI in error reports

src/AppBundle/Model/EventWiki.php, tests/AppBundle/Model/EventWikiTest.php
When we switched to two page ID columns the 2nd one is initally
populated with NULLs. When this is retrieved and decompressed
it results in an empty string, which was being passed through
in the pageIds arrays and breaking SQL.
This patch fixes it by removing any empty elements in the returned
array.
Bug: https://phabricator.wikimedia.org/T213230
=> Prevent empty page IDs when decompressing bzcompressed data

src/AppBundle/Repository/EventCategoryRepository.php, src/AppBundle/Repository/EventWikiRepository.php
The EventWikiRepository::getDbNameFromDomain method was saying
it could return null, but that should never happen. It's better
to throw an exception here (which should also never happen) so
that users of this method can rely on what they get.
This also seems to be what Scrutinizer wants. :-)
=> Remove null possibility for database names

app/config/config.yml, app/config/config_dev.yml, app/config/config_prod.yml
We had monolog configuration in both config.yml and the environment-
specific config (e.g. config_dev.yml). This made everything be logged
twice. This commit makes each environment config have its own monolog
configuration, which has the side effect of ensuring no emails are sent
in the dev environment.
=> Fix double logging; no emails in dev environment

src/AppBundle/DataFixtures/ORM/extended.yml, src/AppBundle/Model/Event.php, src/AppBundle/Model/EventStat.php, src/AppBundle/Model/EventWikiStat.php, src/AppBundle/Repository/EventRepository.php, src/AppBundle/Service/EventProcessor.php, tests/AppBundle/Command/ProcessEventCommandTest.php, tests/AppBundle/Controller/EventDataControllerTest.php, tests/AppBundle/Model/EventTest.php
This extends the current files-uploaded and file-usage metrics to be
computed on all content wikis and not just Commons.
Other very minor code and comment nitpicks.
Bug: https://phabricator.wikimedia.org/T206819
=> Include local file uploads in addition to Commons

app/Resources/views/events/_header.html.twig, app/Resources/views/events/event_summary.wikitext.twig, app/Resources/views/events/revisions.html.twig, app/Resources/views/events/show.html.twig, src/AppBundle/DataFixtures/ORM/extended.yml, src/AppBundle/Model/Event.php, src/AppBundle/Model/Traits/EventStatTrait.php, src/AppBundle/Repository/EventRepository.php, src/AppBundle/Repository/EventWikiRepository.php, src/AppBundle/Service/EventProcessor.php, src/AppBundle/Twig/FormatExtension.php, tests/AppBundle/Controller/EventDataControllerTest.php, tests/AppBundle/Model/EventTest.php
Rename Event::getStartWithTimezone() (and related methods) to
getStartUTC(), to avoid confusion. This commit changes all queries to
use the UTC variant, as it should. In hindsight, we should have stored
datestamps in UTC and only converted for display purposes, but it's
perhaps too late for that.
Make sure the Edit List page shows timestamps in the event's timezone
and not UTC.
Tests were updated to account for the longstanding bugs of using the
non-UTC timestamps in SQL queries.
Other minor code cleanup.
Bug: T215926
=> Fix datestamps in queries and display on Edit List page

app/Resources/views/events/_participants.html.twig, app/Resources/views/events/event_summary.wikitext.twig, app/Resources/views/events/show.html.twig, app/Resources/views/programs/show.html.twig, src/AppBundle/Model/Event.php
Since #173 we are storing Participants as a stat, so the views
automatically show it. This removes the old code that manually showed
the participant count, except for the Participants form where it should
continue to show the count of participants entered.
Bug: T206692
Bug: T216523
=> Don't manually include participants as a stat, is done automatically

app/Resources/views/events/show.html.twig, tests/AppBundle/Controller/EventDataControllerTest.php
Fix test for pages-created; pageviews cumulative of course changes
=> Skip stats that don't exist on Event Summary page

src/AppBundle/Command/ProcessAllEventsCommand.php, tests/AppBundle/Command/ProcessAllEventsCommandTest.php
This is used when we introduce breaking changes to how stats are
generated. It should be used only when necessary.
Bug: T216640
=> Add new Command to process all events

app/Resources/views/events/pages_created.wikitext.twig, src/AppBundle/Controller/EventDataController.php, src/AppBundle/Repository/EventRepository.php, src/AppBundle/Repository/EventWikiRepository.php
Sort by average pageviews. This requires a reworking of the data
structure passed to the view.
Don't include redirects when getting a count of incoming links.
Bug: T205502
=> Sort Pages Created report by avg views; no redirects for incoming links

src/AppBundle/Model/Event.php
In some cases an EventStat object may be present but it has no value
=> Fix Event::getNumParticipants for when there is no EventStat

app/Resources/views/events/event_summary.wikitext.twig, i18n/en.json, i18n/qqq.json, src/AppBundle/Model/Event.php, src/AppBundle/Model/EventStat.php, src/AppBundle/Repository/EventRepository.php, src/AppBundle/Service/EventProcessor.php, tests/AppBundle/Command/ProcessEventCommandTest.php, tests/AppBundle/Controller/EventDataControllerTest.php, tests/AppBundle/Model/EventTest.php
Required some reworking of how the 'Unique pages with uploaded files'
was implemented.
Bug: T206700
=> Add 'Avg. daily views to pages that have uploaded files' metric

app/Resources/views/events/event_summary.csv.twig
As discussed with Joe, this is preventing spreadsheets from understanding
the number.
=> Remove + from byte difference in the CSV report

src/AppBundle/Repository/Repository.php
Pages Created report uses an array of the page IDs, which might be too
large for a cache key. This commit uses a md5 hash of that array to
ensure the key is of reasonable length.
=> Shorten cache keys

src/AppBundle/Repository/EventRepository.php, src/AppBundle/Repository/EventWikiRepository.php, src/AppBundle/Repository/PageviewsRepository.php, src/AppBundle/Service/EventProcessor.php, tests/AppBundle/Repository/PageviewsRepositoryTest.php
This required some reworking of the pageviews methods, to accept a
domain rather than an EventWiki. For impact of Commons uploads, we look
at all wikis, whether or not they are configured for the Event.
Bug: T206700
=> Make 'pages-using-files-pageviews-avg' metric apply to all wikis

src/AppBundle/Repository/EventWikiRepository.php, tests/AppBundle/Repository/EventWikiRepositoryTest.php
That is, the age or the 'offset' (currently 30 days), whatever is shorter.
Depends on: #206
Bug: T206700
=> Use age of article when calculating average pageviews

app/Resources/views/events/event_summary.wikitext.twig, app/Resources/views/events/pages_created.wikitext.twig, tests/AppBundle/Controller/EventDataControllerTest.php
Some cleanup to event summary wikitext template to make it more
readable.
Bug: T205502
=> Right-align numeric data in wikitext reports

src/AppBundle/Repository/EventWikiRepository.php, src/AppBundle/Repository/PageviewsRepository.php, tests/AppBundle/Repository/EventWikiRepositoryTest.php, tests/AppBundle/Repository/PageviewsRepositoryTest.php
Account for gaps in timeseries when computing avg pageviews.
Ensure average pageviews is in relation to how long the article existed.
Refactor some pageviews logic to PageviewsRepository. In an ideal world
where we follow best practices, PageviewsRepository wouldn't have any
logic beyond fetching the data itself. But, we're breaking the same rule
in EventWikiRepository (and the others), so this refactoring at least
moves all the core pageviews logic into the same file.
Bug: T217704
=> [WIP] Fix various bugs with pageviews; some refactoring

app/Resources/views/events/pages_created.csv.twig, app/Resources/views/events/pages_created.wikitext.twig, app/Resources/views/macros/wiki.html.twig, tests/AppBundle/Controller/EventDataControllerTest.php
=> URL-encode page titles in Twig templates, and use raw in CSV export

src/AppBundle/Repository/EventWikiRepository.php, src/AppBundle/Repository/PageviewsRepository.php, tests/AppBundle/Repository/EventWikiRepositoryTest.php, tests/AppBundle/Repository/PageviewsRepositoryTest.php
Account for gaps in timeseries when computing avg pageviews.
Ensure average pageviews is in relation to how long the article existed.
Refactor some pageviews logic to PageviewsRepository. In an ideal world
where we follow best practices, PageviewsRepository wouldn't have any
logic beyond fetching the data itself. But, we're breaking the same rule
in EventWikiRepository (and the others), so this refactoring at least
moves all the core pageviews logic into the same file.
Bug: T217704
=> Fix various bugs with pageviews; some refactoring

src/AppBundle/Repository/PageviewsRepository.php
In computing averages, we look for pageviews only in the past 31 days.
If there are none, $lastAvgDate doesn't get set and an exception is
thrown. This commit fixes this and has it simply return 0 as the
average.
Bug: T217704
=> Return 0 for avg pageviews if there were no recent pageviews

src/AppBundle/Repository/EventWikiRepository.php
Pageviews API takes at least 24 hours to populate.
Bug: T217704
=> End date for pageviews should always be yesterday at midnight

src/AppBundle/Service/JobHandler.php, tests/AppBundle/Controller/DatabaseAwareWebTestCase.php, tests/AppBundle/Controller/EventDataControllerTest.php
Apparently they persist, which can cause you to hit the 5-connection
limit imposed on the replicas. This issue is intermittent.
Also throw Exception in JobHandler when db connection limit is hit,
so that it's more clear what went wrong.
=> Kill active database connections between tests

src/AppBundle/Repository/EventWikiRepository.php, src/AppBundle/Service/EventProcessor.php, tests/AppBundle/Command/ProcessEventCommandTest.php
This commit is a subset of #217
Remove "quick cache" crap in EventProcessor. This was caching things
between requests (or at least between integration tests), causing
erroneous results. Instead we'll use a class property to cache the
usernames.
ix timestamps in EventWikiRepository::getUsersFromPageIDs(). They should
be in UTC.
Bug: T205734
=> Rm static caching in EventProcessor; fix timestamps when fetching users

src/AppBundle/Model/EventWiki.php, src/AppBundle/Repository/EventRepository.php, tests/AppBundle/Controller/EventDataControllerTest.php
Unclear why this change requires us to manually kill db connections
between test cases. I've put in a TODO to investigate at a later time.
Bug: T218582
=> Fix used files metric following #222 refactor

app/Resources/views/events/show.html.twig, src/AppBundle/Controller/EventController.php, src/AppBundle/DataFixtures/ORM/extended.yml, src/AppBundle/Model/Event.php, src/AppBundle/Model/EventStat.php, src/AppBundle/Model/EventWiki.php, src/AppBundle/Model/Traits/EventStatTrait.php, src/AppBundle/Repository/EventRepository.php, src/AppBundle/Repository/EventWikiRepository.php, src/AppBundle/Service/EventProcessor.php, tests/AppBundle/Command/ProcessEventCommandTest.php, tests/AppBundle/Controller/EventDataControllerTest.php, tests/AppBundle/Model/EventWikiTest.php
Add support for categories without participants
This can still fail very large categories, but we'll iron out performance
issues later. Most categories process just fine without any error.
Some metrics don't apply when there are no participants, such as local
file uploads (there could be thousands, most presumably unrelated to the
event). To address this, we introduce EventWiki::canHaveFilesUploaded()
and also EventWiki::isValid(). The latter ensures there are at least
some participants or one category to work with.
Remove unused EventController::getEventStats().
Other minor code cleanup.
Bug: T205734
=> Add support for categories without participants

app/Resources/views/events/event_summary.wikitext.twig
Bug: https://phabricator.wikimedia.org/T217083
=> Tweak order of stats in wikitext event summary

app/DoctrineMigrations/Version20190322001628.php, src/AppBundle/Model/EventWiki.php, src/AppBundle/Repository/EventWikiRepository.php, src/AppBundle/Service/EventProcessor.php, tests/AppBundle/Command/ProcessEventCommandTest.php, tests/AppBundle/Model/EventWikiTest.php, tests/AppBundle/Repository/EventWikiRepositoryTest.php
This was semi-fixed before, but still broke if a participant edited the
page after creating it.
Writing a query that looked for unique pages edited, but not created, by
a list of users and/or within a category, turned out too be a mess and
possibly infeasible. Instead, we fetch the pages created then edited,
and subtract the arrays. This logic is handled in EventProcessor.
Other minor code refactoring.
Bug: T217455
=> Exclude pages created from pages improved and rename the entity property

composer.json, composer.lock, tests/AppBundle/Command/SpawnJobsCommandTest.php, tests/AppBundle/Controller/DefaultControllerTest.php, tests/AppBundle/Controller/EventControllerTest.php, tests/AppBundle/Controller/EventDataControllerTest.php, tests/AppBundle/Controller/ProgramControllerTest.php
assertArraySubset is going to removed entirely with no alternative,
so we are now using dms/phpunit-arraysubset-asserts
=> Fix phpunit deprecations

app/Resources/views/events/_participants.html.twig, app/Resources/views/events/show.html.twig
Show all bullet points unless the event is for Wikidata *only*,
and show the normal participants' form panel message.
Bug: T218340
=> Adjust error display for Wikidata events

src/AppBundle/Form/CategoriesType.php
There is suerly a more proper way to do this in Symfony Forms, but this
works and mimics what we're already doing for ParticipantType.
At some point I would like to improve test coverage for the forms, where
we are adding/removing elements, but this is tedious to do and should be
saved for a separate PR.
Bug: T219732
=> Use existing EventCategory when submitting duplicate

app/Resources/views/_attribution.html.twig, app/Resources/views/base.html.twig, app/Resources/views/blocks/forms.html.twig, app/Resources/views/events/_categories.html.twig, app/Resources/views/events/_form.html.twig, app/Resources/views/events/_header.html.twig, app/Resources/views/events/_metadata.html.twig, app/Resources/views/events/_participants.html.twig, app/Resources/views/events/revisions.html.twig, app/Resources/views/events/revisions.wikitext.twig, app/Resources/views/events/show.html.twig, app/Resources/views/macros/layout.html.twig, app/Resources/views/programs/_form.html.twig, app/Resources/views/programs/index.html.twig, app/Resources/views/programs/show.html.twig, composer.json, composer.lock
There is one bug affecting us with setting variables in a loop, see
https://github.com/allocine/twigcs/issues/35. This can be avoided
by adding a {# twigcs use-var my_var #} comment above the offending
line.
=> Add linter for Twig, using the official Twig standard

app/Resources/views/events/show.html.twig, src/AppBundle/Controller/EventController.php, src/AppBundle/Model/Event.php
The list of unfiltered wikis was excluding Wikidata because it
does not have categories. This adds a new method to retrieve the
uncategorized wikis and Wikidat in addition if there are no
participants.
Bug: T218340
=> Give full list of all unfiltered wikis

app/Resources/views/events/_participants.html.twig
Change from only showing the 'required for Wikidata' message when
Wikidata is the only wiki, to showing it whenever there are no
participants and Wikidata is any one of the wikis.
Bug: T218340
=> Show error on participants panel for any Wikidata event

app/Resources/views/events/_header.html.twig, src/AppBundle/EventSubscriber/EventDataSubscriber.php, tests/AppBundle/Controller/DatabaseAwareWebTestCase.php, tests/AppBundle/Controller/EventDataControllerTest.php
This check used to exist but somehow got removed. The idea
is that you don't want to allow the user to run a report because
the update will change the page IDs that the report depends on.
=> Disallow access to reports during an update

src/AppBundle/Service/JobHandler.php
...instead of nuking them outright.
Bug: T220423
=> Mark long running jobs as timed out

src/AppBundle/Repository/EventWikiRepository.php, src/AppBundle/Repository/PageviewsRepository.php, src/AppBundle/Service/EventProcessor.php
Prevent temporary network glitches from slowing down the process unduly.
At the same time, retry in case the problem was a one-off.
Bug: T219897
=> PageviewsRepository: introduce HTTP retries and timeouts

src/AppBundle/Repository/EventWikiRepository.php, src/AppBundle/Repository/PageviewsRepository.php, tests/AppBundle/Repository/PageviewsRepositoryTest.php
This only covers fetching of pageviews during a normal update.
The reports still need to be converted to be async.
PageviewsRepository::getAggregate() was removed as it is not used and
unlikely to be used in the future.
Bug: T217911
=> Fetch pageviews asynchronously, max 100 per second

src/AppBundle/Repository/EventWikiRepository.php, src/AppBundle/Repository/Repository.php, src/AppBundle/Service/EventProcessor.php, tests/AppBundle/Repository/EventWikiRepositoryTest.php, tests/AppBundle/Repository/RepositoryTest.php
Only a few uses are covered because this is just an attempt to organize
the actors support, however this change is self-contained and can be
merged on its own.
Bug: T219328
=> Start using the actors table
